In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.float64(np.array([[2,0,1],
         [0,5,0],
         [1,0,2]]))
b = np.float64(np.array([3,-5,3]))
x0 = np.float64(np.array([0,0,1/2]))
x0

array([0. , 0. , 0.5])

In [3]:
def grad(A,b,x0, maxiter):
    """
        Gradient method for solving Ax =b
        
        Parameters:
                    A: nxn matrix
                    b: nx1 constants vector
                    x0: starting input for algorithm
                    maxiter: number of iterations
                    
        Returns:
                x: approximation of solution, nx1 vector
    """
    x = np.copy(x0)
    Ax = np.matmul(A,x)
    r = b-Ax
    print_start(x,r)
    for k in range(maxiter):
        norm_r_2 = LA.norm(r,2)
        Ar = np.matmul(A,r)
        norm_r_A = np.matmul(r,Ar)
        ak = np.square(norm_r_2)/norm_r_A
        x += ak*r
        r -= ak *Ar
        print_status_for_every_iter(k,ak,x,r)
        
    return x

def print_start(x0,r0):
    print("Starting with")
    print("x_0 = ", x0)
    print("r_0 = ", r0)
    print("")
    
def print_status_for_every_iter(k,ak,x,r):
    print("Iteration k=",k)
    print("a_{} =".format(k), ak)
    print("x_{} = ".format(k+1),x)
    print("r_{} = ".format(k+1),r)
    print("")
    

In [4]:
sol_grad = grad(A,b,x0, maxiter = 2)

Starting with
x_0 =  [0.  0.  0.5]
r_0 =  [ 2.5 -5.   2. ]

Iteration k= 0
a_0 = 0.2266881028938907
x_1 =  [ 0.56672026 -1.13344051  0.95337621]
r_1 =  [0.91318328 0.66720257 0.52652733]

Iteration k= 1
a_1 = 0.2876859448652138
x_2 =  [ 0.82943025 -0.94149571  1.10485072]
r_2 =  [ 0.23628878 -0.29252144 -0.03913169]



In [5]:
def conj_grad(A, b, x0, maxiter = 2):
    """
    Conjugate graduate method for solving Ax=b
    
    Parameters:
                A: nxn matrix
                b: nx1 constants vector
                x0: starting input for algorithm
                maxiter: number of iterations
                    
        Returns:
                x: approximation of solution, nx1 vector
    """
    x = np.copy(x0)
    Ax = np.matmul(A,x) 
    r = b - Ax
    p = np.copy(r)
    print("Starting with:")
    print("x_0 = ", x)
    print("r_0 = ", r)
    print("p_0 = ", p)
    print("")
    for k in range(maxiter):
        Ap = np.matmul(A,p)
        norm_p_A = np.matmul(p,Ap)
        ak = np.dot(p,r)/norm_p_A
        x += ak * p
        r += r - ak * Ap
        bk = np.matmul(Ap,r) / np.matmul(Ap, p)
        p = r - bk * p
        
        print("a_{} = ".format(k), ak)
        print("x_{} = ".format(k+1), x)
        print("r_{} = ".format(k+1), r)
        print("b_{} = ".format(k), bk)
        print("p_{} = ".format(k+1), p)
        print("")
    return x

In [6]:
sol_conj = conj_grad(A,b,x0,maxiter = 2)

Starting with:
x_0 =  [0.  0.  0.5]
r_0 =  [ 2.5 -5.   2. ]
p_0 =  [ 2.5 -5.   2. ]

a_0 =  0.2266881028938907
x_1 =  [ 0.56672026 -1.13344051  0.95337621]
r_1 =  [ 3.41318328 -4.33279743  2.52652733]
b_0 =  0.9558498154485581
p_1 =  [1.02355874 0.44645165 0.6148277 ]

a_1 =  0.6095236423304586
x_2 =  [ 1.19060351 -0.86131768  1.32812823]
r_2 =  [  5.20384804 -10.02620903   3.67966737]
b_1 =  -0.04653809866906776
p_2 =  [  5.25148251 -10.00543202   3.70828028]



In [7]:
print(sol_grad)
print(sol_conj)

[ 0.82943025 -0.94149571  1.10485072]
[ 1.19060351 -0.86131768  1.32812823]


In [8]:
np.linalg.solve(A,b)

array([ 1., -1.,  1.])