In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.float64(np.array([[2,0,1],
         [0,5,0],
         [1,0,2]]))
b = np.float64(np.array([3,-5,3]))
x0 = np.float64(np.array([0,0,1/2]))
x0

array([0. , 0. , 0.5])

In [3]:
def grad(A,b,x0, maxiter, print_everything = True):
    """
        Gradient method for solving Ax =b
        
        Parameters:
                    A: nxn matrix
                    b: nx1 constants vector
                    x0: starting input for algorithm
                    maxiter: number of iterations
                    
        Returns:
                x: approximation of solution, nx1 vector
    """
    x = np.copy(x0)
    Ax = np.matmul(A,x)
    r = b-Ax
    if print_everything: print_start_grad(x,r)
    for k in range(maxiter):
        norm_r_2 = LA.norm(r,2)
        Ar = np.matmul(A,r)
        norm_r_A = np.matmul(r,Ar)
        ak = np.square(norm_r_2)/norm_r_A
        x += ak*r
        r -= ak *Ar
        if print_everything: print_status_for_every_iter_grad(k,ak,x,r)
        
    return x

def print_start_grad(x0,r0):
    print("Starting with")
    print("x_0 = ", x0)
    print("r_0 = ", r0)
    print("")
    
def print_status_for_every_iter_grad(k,ak,x,r):
    print("Iteration k=",k)
    print("a_{} =".format(k), ak)
    print("x_{} = ".format(k+1),x)
    print("r_{} = ".format(k+1),r)
    print("")
    

In [4]:
sol_grad = grad(A,b,x0, maxiter = 2)

Starting with
x_0 =  [0.  0.  0.5]
r_0 =  [ 2.5 -5.   2. ]

Iteration k= 0
a_0 = 0.2266881028938907
x_1 =  [ 0.56672026 -1.13344051  0.95337621]
r_1 =  [0.91318328 0.66720257 0.52652733]

Iteration k= 1
a_1 = 0.2876859448652138
x_2 =  [ 0.82943025 -0.94149571  1.10485072]
r_2 =  [ 0.23628878 -0.29252144 -0.03913169]



In [5]:
def conj_grad(A, b, x0, maxiter = 2, print_everything = True):
    """
    Conjugate graduate method for solving Ax=b
    
    Parameters:
                A: nxn matrix
                b: nx1 constants vector
                x0: starting input for algorithm
                maxiter: number of iterations
                    
        Returns:
                x: approximation of solution, nx1 vector
    """
    x = np.copy(x0)
    Ax = np.matmul(A,x) 
    r = b - Ax
    p = np.copy(r)
    if print_everything: print_start_conj(x,r,p)
    for k in range(maxiter):
        Ap = np.matmul(A,p)
        ak = np.matmul(p,r)/np.matmul(p,Ap)
        x += ak * p
        r -= ak * Ap
        bk = np.matmul(Ap,r) / np.matmul(Ap, p)
        p = r - bk * p
        if print_everything: print_iteration_conj(k,ak,x,r,bk,p)
    return x

def print_start_conj(x,r,p):
        print("Starting with:")
        print("x_0 = ", x)
        print("r_0 = ", r)
        print("p_0 = ", p)
        print("")

def print_iteration_conj(k,ak,x,r,bk,p):     
        print("a_{} = ".format(k), ak)
        print("x_{} = ".format(k+1), x)
        print("r_{} = ".format(k+1), r)
        print("b_{} = ".format(k), bk)
        print("p_{} = ".format(k+1), p)
        print("")

In [6]:
sol_conj = conj_grad(A,b,x0,maxiter = 2)

Starting with:
x_0 =  [0.  0.  0.5]
r_0 =  [ 2.5 -5.   2. ]
p_0 =  [ 2.5 -5.   2. ]

a_0 =  0.2266881028938907
x_1 =  [ 0.56672026 -1.13344051  0.95337621]
r_1 =  [0.91318328 0.66720257 0.52652733]
b_0 =  -0.04415018455144181
p_1 =  [1.02355874 0.44645165 0.6148277 ]

a_1 =  0.30476182116522854
x_2 =  [ 0.87866188 -0.9973791   1.14075222]
r_2 =  [ 0.10192402 -0.01310452 -0.16016631]
b_1 =  -0.023269049334537325
p_2 =  [ 0.12574126 -0.00271601 -0.14585986]



In [7]:
print(sol_grad)
print(sol_conj)

[ 0.82943025 -0.94149571  1.10485072]
[ 0.87866188 -0.9973791   1.14075222]


In [8]:
# real solution
np.linalg.solve(A,b)

array([ 1., -1.,  1.])

In [9]:
LA.eigh(A)

(array([1., 3., 5.]),
 array([[-0.70710678, -0.70710678,  0.        ],
        [ 0.        ,  0.        , -1.        ],
        [ 0.70710678, -0.70710678,  0.        ]]))

In [10]:
# Better approximation for grad
sol_grad = grad(A,b,x0, maxiter = 43, print_everything=False)
sol_grad

array([ 1., -1.,  1.])

In [11]:
# Better approximation for conj grad
sol_conj = conj_grad(A,b,x0,maxiter = 3, print_everything=False)
sol_conj

array([ 1., -1.,  1.])